version: '3'
services:
  tensorflow:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    ports:
      - "8888:8888"
    volumes:
      - my_tf_notebooks:/tf/my_tf_notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
volumes:
  my_tf_notebooks: